name: Godot

on: push

jobs:
  rust:
    runs-on: ubuntu-latest
    name: Building Rust source
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Upload GDNative library as artifact
      uses: actions/upload-artifact@v1
      with:
        name: gdnativelib
        path: target/release/libcore.so
  linux:
    name: Building Godot game for Linux/X11
    container: godot-ci:latest
    steps:
    - name: Download GDNative library artifact
      uses: actions/download-artifact@v1
      with:
        name: gdnativelib
        path: target/release/libcore.so
    - name: Building for Linux/X11
      run: godot -v --export "Linux/X11" ./build/linux/sample_godot_rust_app.x86_64