name: Linux CI

# Uncomment if the workflow should be triggered by whatever push
on: push

# Uncomment all these lines if the workflow should be triggered only for source code changes
# on:
#   push:
#     paths:
#     - 'dockerfiles/**'
#     - 'assets/**'
#     - 'scenes/**'
#     - 'src/**'
#     - 'project.godot'
#     - 'default_env.tres'
#     - 'Cargo.toml'
#     - 'export_presets.cfg'

jobs:
  # This job is where we test Rust source code and then compile it for Linux target
  rust-linux:
    runs-on: ubuntu-latest
    name: Building Rust source for Linux
    steps:
    - uses: actions/checkout@v2
    - name: Check Rust toolchain
      run: rustup show
    - name: Run tests
      run: cargo test --release
    - name: Build
      run: cargo build --release
    - name: Upload GDNative library as artifact
      uses: actions/upload-artifact@v1
      with:
        name: libcore.so
        path: target/release/libcore.so