name: Windows CI

# Uncomment if the workflow should be triggered by whatever push
on: push

# Uncomment all these lines if the workflow should be triggered only for source code changes
# on:
#   push:
#     paths:
#     - 'dockerfiles/**'
#     - 'assets/**'
#     - 'scenes/**'
#     - 'src/**'
#     - 'project.godot'
#     - 'default_env.tres'
#     - 'Cargo.toml'
#     - 'export_presets.cfg'

jobs:
  # This job is where we compile Rust source code for Windows target
  rust-windows:
    runs-on: ubuntu-latest
    name: Building Rust source for Windows
    steps:
    - uses: actions/checkout@v2
    - name: Check Rust toolchain
      run: rustup show
    - name: Install Cross
      run: cargo install cross
    - name: Build custom Docker image for x86_64-pc-windows-gnu toolchain with LLVM
      run: docker build -t my/x86_64-pc-windows-gnu:latest -f ./dockerfiles/x86_64-pc-windows-gnu.Dockerfile .
    - name: Build with Cross
      run: cross build --release --target x86_64-pc-windows-gnu
    - name: Upload GDNative library as artifact
      uses: actions/upload-artifact@v1
      with:
        name: core.dll
        path: target/x86_64-pc-windows-gnu/release/core.dll