name: Sandbox

on: push

jobs:
  # job1:
  #   runs-on: ubuntu-latest
  #   name: Just trying out some commands in CI
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Check Rust toolchain
  #     run: rustup show
  #   - name: Build custom Docker image for armv7-linux-androideabi toolchain with LLVM
  #     run: docker build -t my/armv7-linux-androideabi:latest -f ./dockerfiles/armv7-linux-androideabi.Dockerfile .

  job2:
    runs-on: ubuntu-latest
    name: Looking into Ubuntu environment
    steps:
    - name: Echo ANDROID_HOME
      run: echo $ANDROID_HOME
    - name: Check ANDROID_HOME
      run: ls $ANDROID_HOME
    - name: Check ANDROID_HOME/ndk
      run: ls $ANDROID_HOME/ndk
    - name: Check ANDROID_HOME/ndk-bundle
      run: ls $ANDROID_HOME/ndk-bundle
    - name: Check NDK toolchains
      run: ls $ANDROID_HOME/ndk-bundle/toolchains
    - name: Check NDK toolchains
      run: ls $ANDROID_HOME/ndk-bundle/toolchains
    - name: Check NDK toolchains binaries for Linux
      run: ls $ANDROID_HOME/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/
    - name: Check JAVA_HOME
      run: ls $JAVA_HOME
    - name: Check JAVA_HOME/include
      run: ls $JAVA_HOME/include
    - name: Check JAVA_HOME/include
      run: ls $JAVA_HOME/include/linux
    - name: Try to find GCC
      run: which gcc