# This workflow is intended for Ubuntu environment troubleshooting and common UNIX command testing 
name: Sandbox

# Uncomment if the workflow should be triggered by whatever push
on: push

# Uncomment all these lines if the workflow should be triggered only for source code changes
# on:
#   push:
#     paths:
#     - 'dockerfiles/**'
#     - 'assets/**'
#     - 'scenes/**'
#     - 'src/**'
#     - 'project.godot'
#     - 'default_env.tres'
#     - 'Cargo.toml'
#     - 'export_presets.cfg'

jobs:
  godot-android-sandbox:
    runs-on: ubuntu-latest
    name: Trying to setup Godot Engine to support Android exports
    steps:
    - uses: actions/checkout@v2
    - name: Display $JAVA_HOME
      run: echo $JAVA_HOME
    - name: Display $ANDROID_HOME
      run: echo $ANDROID_HOME
    - name: Display pwd and $GITHUB_WORKSPACE
      run: |
        pwd
        echo $GITHUB_WORKSPACE
    - name: Trying to locate jarsigner
      run: ls $JAVA_HOME/bin
    - name: Trying to locate adb
      run: ls $ANDROID_HOME/platform-tools
    - name: Trying to locate debug.keystore
      run: |
        keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"
        ls
    - name: Setup environment
      run: |
        wget https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_linux_headless.64.zip
        wget https://downloads.tuxfamily.org/godotengine/3.2.1/Godot_v3.2.1-stable_export_templates.tpz
        mkdir ~/.cache
        mkdir -p ~/.config/godot
        mkdir -p ~/.local/share/godot/templates/3.2.1.stable
        unzip Godot_v3.2.1-stable_linux_headless.64.zip
        sudo mv Godot_v3.2.1-stable_linux_headless.64 /usr/local/bin/godot
        unzip Godot_v3.2.1-stable_export_templates.tpz
        sudo mv templates/* ~/.local/share/godot/templates/3.2.1.stable
        sudo rm -f Godot_v3.2.1-stable_linux_headless.64.zip Godot_v3.2.1-stable_export_templates.tpz
        mkdir -p ./build/android
    - name: Trying to locate editor settings
      run: ls ~/.config
    - name: Trying to locate editor settings deeper
      run: ls ~/.config/godot
    - name: Just checking something
      run: ls ~/.local/share/godot
    - name: Write editor settings
      run: |
        touch ~/.config/godot/editor_settings-3.tres
        echo '[gd_resource type="EditorSettings" format=2]' >> ~/.config/godot/editor_settings-3.tres
        echo '[resource]' >> ~/.config/godot/editor_settings-3.tres
        echo 'export/android/adb = "$ANDROID_HOME/platform-tools/adb"' >> ~/.config/godot/editor_settings-3.tres
        echo 'export/android/jarsigner = "$JAVA_HOME/bin/jarsigner"' >> ~/.config/godot/editor_settings-3.tres
        echo 'export/android/debug_keystore = "/home/runner/debug.keystore"' >> ~/.config/godot/editor_settings-3.tres
        echo 'export/android/debug_keystore_user = "androiddebugkey"' >> ~/.config/godot/editor_settings-3.tres
        echo 'export/android/debug_keystore_pass = "android"' >> ~/.config/godot/editor_settings-3.tres
        echo 'export/android/force_system_user = false' >> ~/.config/godot/editor_settings-3.tres
        echo 'export/android/custom_build_sdk_path = ""' >> ~/.config/godot/editor_settings-3.tres
        echo 'export/android/timestamping_authority_url = ""' >> ~/.config/godot/editor_settings-3.tres
        echo 'export/android/shutdown_adb_on_exit = true' >> ~/.config/godot/editor_settings-3.tres
        cat ~/.config/godot/editor_settings-3.tres
        
        
        
        
        
        
        
        
        

        