name: Sandbox

on: push

jobs:
  android-tryout-1:
    runs-on: ubuntu-latest
    name: Building Rust source for Linux
    steps:
    - uses: actions/checkout@v2
    - name: Check Rust toolchain
      run: rustup show
    - name: Build custom Docker image for armv7-linux-androideabi toolchain with LLVM
      run: docker build -t my/armv7-linux-androideabi:latest -f ./dockerfiles/armv7-linux-androideabi.Dockerfile .

