# This workflow is intended for Ubuntu environment troubleshooting and common UNIX command testing 
name: Sandbox

# Uncomment if the workflow should be triggered by whatever push
on: push

# Uncomment all these lines if the workflow should be triggered only for source code changes
# on:
#   push:
#     paths:
#     - 'dockerfiles/**'
#     - 'assets/**'
#     - 'scenes/**'
#     - 'src/**'
#     - 'project.godot'
#     - 'default_env.tres'
#     - 'Cargo.toml'
#     - 'export_presets.cfg'

jobs:
  godot-android-setup:
    runs-on: ubuntu-latest 
    name: Trying to setup Godot Engine to support Android exports
    steps:
    - uses: actions/checkout@v2
    - name: Try to generate a keystore
      env:
        ANDROID_RELEASE_KEYSTORE: ${{ secrets.ANDROID_RELEASE_KEYSTORE }}
        ANDROID_RELEASE_KEYSTORE_USER: ${{ secrets.ANDROID_RELEASE_KEYSTORE_USER }}
        ANDROID_RELEASE_KEYSTORE_PASS: ${{ secrets.ANDROID_RELEASE_KEYSTORE_PASS }}
      run: keytool -genkey -v -keystore "$ANDROID_RELEASE_KEYSTORE" -storepass "$ANDROID_RELEASE_KEYSTORE_PASS" -alias "$ANDROID_RELEASE_KEYSTORE_USER" -keypass "$ANDROID_RELEASE_KEYSTORE_PASS" -sigalg MD5withRSA -keyalg RSA -keysize 2048 -validity 10000 -dname "C=US, O=Android, CN=Android Debug"
    - name: Try to build Docker image from myood/godot-ci-android-export 
      run: docker build -t my/godot-ci:latest -f ./dockerfiles/godot-ci.Dockerfile .
    
        
        
        
        
        
        
        
        
        

        